dubbo:
  application:
    logger: slf4j
    name: DemoApplication
  registry:
    address: zookeeper://${zookeeper.address:81.68.154.99}:2181?timeout=60000
    timeout: 300000
    parameters:
      blockUntilConnectedWait: 250
  protocol:
    name: tri
    port: 50051
